#pragma once

/************************************************************
            automatically generated by hands
                do not edit (please)
************************************************************/

#define fuku_assambler_arith_add 0
#define fuku_assambler_arith_or  1
#define fuku_assambler_arith_adc 2
#define fuku_assambler_arith_sbb 3
#define fuku_assambler_arith_and 4
#define fuku_assambler_arith_sub 5
#define fuku_assambler_arith_xor 6
#define fuku_assambler_arith_cmp 7

#define fuku_assambler_arith_ex_not  2
#define fuku_assambler_arith_ex_neg  3
#define fuku_assambler_arith_ex_mul  4
#define fuku_assambler_arith_ex_imul 5
#define fuku_assambler_arith_ex_div  6
#define fuku_assambler_arith_ex_idiv 7

#define fuku_assambler_arith_inc 0
#define fuku_assambler_arith_dec 1

#define fuku_assambler_shift_rol 0
#define fuku_assambler_shift_ror 1
#define fuku_assambler_shift_rcl 2
#define fuku_assambler_shift_rcr 3
#define fuku_assambler_shift_shl 4
#define fuku_assambler_shift_shr 5
#define fuku_assambler_shift_sar 7

#define fuku_assambler_bittest_bt  4
#define fuku_assambler_bittest_bts 5
#define fuku_assambler_bittest_btr 6
#define fuku_assambler_bittest_btc 7

#define fuku_assambler_string_out 55
#define fuku_assambler_string_mov 82
#define fuku_assambler_string_cmp 83
#define fuku_assambler_string_sto 85
#define fuku_assambler_string_lod 86
#define fuku_assambler_string_sca 87

#include "fuku_assambler_pattern_macro.h"

static uint64_t di_fl_jcc[] = {
        X86_EFLAGS_TEST_OF , X86_EFLAGS_TEST_OF,
        X86_EFLAGS_TEST_CF , X86_EFLAGS_TEST_CF,
        X86_EFLAGS_TEST_ZF , X86_EFLAGS_TEST_ZF,
        X86_EFLAGS_TEST_ZF | X86_EFLAGS_TEST_CF, X86_EFLAGS_TEST_ZF | X86_EFLAGS_TEST_CF,
        X86_EFLAGS_TEST_SF , X86_EFLAGS_TEST_SF,
        X86_EFLAGS_TEST_PF , X86_EFLAGS_TEST_PF,
        X86_EFLAGS_TEST_OF | X86_EFLAGS_TEST_SF, X86_EFLAGS_TEST_OF | X86_EFLAGS_TEST_SF,
        X86_EFLAGS_TEST_OF | X86_EFLAGS_TEST_SF | X86_EFLAGS_TEST_ZF, X86_EFLAGS_TEST_OF | X86_EFLAGS_TEST_SF | X86_EFLAGS_TEST_ZF
};





#define gen_func_body_onebyte_no_arg(name ,byte, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: _##name## () { \
        gencleanerdata\
        emit_b(byte);\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_twobyte_no_arg(name ,byte1,byte2, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: _##name## () { \
        gencleanerdata\
        emit_b(byte1);\
        emit_b(byte2);\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_threebyte_no_arg(name ,byte1,byte2,byte3, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: _##name## () { \
        gencleanerdata\
        emit_b(byte1);\
        emit_b(byte2);\
        emit_b(byte3);\
        gen_func_return(cap_id, cap_eflags)\
    } 


#define gen_func_body_ff_r(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,) (fuku_register src) { \
        gencleanerdata\
        emit_optional_rex_32(src);\
        emit_b(0xFF);\
        emit_modrm(src, type);\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_ff_offset(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,) (const fuku_immediate& src) { \
        gencleanerdata\
        emit_b(type);\
        emit_immediate_dw(src);\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_ff_op(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,) (const fuku_operand& src) { \
        gencleanerdata\
        emit_optional_rex_32(src);\
        emit_b(0xFF);\
        emit_operand(src, (fuku_register_index)type);\
        gen_func_return(cap_id, cap_eflags)\
    } 










#define gen_func_body_arith(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_r(8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_optional_rex_32(dst);\
        if(is_used_short_eax() && dst == fuku_register::FUKU_REG_AL) {\
            emit_b(0x04 + 8*type); \
        } else {\
            emit_b(0x80); \
            emit_modrm(dst, type);\
        }\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (fuku_register dst,const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx(0x02 + 8*type, src, dst)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_optional_rex_32(dst);\
        emit_b(0x80);\
        emit_operand(dst, (fuku_register_index)type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_op_r(0x00 + 8 * type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_r_word(0x01 + 8 * type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_optional_rex_32(dst);\
        if(is_used_short_eax() && dst == fuku_register::FUKU_REG_AX) {\
            emit_b(0x05 + 8*type); \
            emit_immediate_w(src);\
        } else {\
            if (is_used_short_imm() && src.is_8()) {\
                emit_b(0x83);\
                emit_modrm(dst, type);\
                emit_immediate_b(src);\
            }else{\
                emit_b(0x81);\
                emit_modrm(dst, type);\
                emit_immediate_w(src);\
            }\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register dst,const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_r_word(0x03 + 8*type, src, dst)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_op_r_word(0x01 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_optional_rex_32(dst);\
        if (is_used_short_imm() && src.is_8()) {\
            emit_b(0x83);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_b(src);\
        }else{\
            emit_b(0x81);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_w(src);\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_r(0x01 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
         emit_optional_rex_32(dst);\
         if(is_used_short_eax() && dst == fuku_register::FUKU_REG_EAX) {\
            emit_b(0x05 + 8*type); \
            emit_immediate_dw(src);\
        } else {\
            if (is_used_short_imm() && src.is_8()) {\
                emit_b(0x83);\
                emit_modrm(dst, type);\
                emit_immediate_b(src);\
            }else{\
                emit_b(0x81);\
                emit_modrm(dst, type);\
                emit_immediate_dw(src);\
            }\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register dst,const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_r(0x03 + 8*type, src, dst)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_op_r(0x01 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_optional_rex_32(dst);\
         if (is_used_short_imm() && src.is_8()) {\
            emit_b(0x83);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_b(src);\
        }else{\
            emit_b(0x81);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_dw(src);\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern64_1em_rm_r(0x01 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
         emit_rex_64(dst); \
         if(is_used_short_eax() && dst == fuku_register::FUKU_REG_RAX) {\
            emit_b(0x05 + 8*type); \
            emit_immediate_dw(src);\
        } else {\
            if (is_used_short_imm() && src.is_8()) {\
                emit_b(0x83);\
                emit_modrm(dst, type);\
                emit_immediate_b(src);\
            }else{\
                emit_b(0x81);\
                emit_modrm(dst, type);\
                emit_immediate_dw(src);\
            }\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register dst,const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern64_1em_op_r(0x03 + 8*type, src, dst)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern64_1em_op_r(0x01 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
         emit_rex_64(dst); \
         if (is_used_short_imm() && src.is_8()) {\
            emit_b(0x83);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_b(src);\
        }else{\
            emit_b(0x81);\
            emit_operand(dst, (fuku_register_index)type);\
            emit_immediate_dw(src);\
        }\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_arith_ex_one_op(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx(0xF6, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx(0xF6, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx_word(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx_word(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register src) { \
        gencleanerdata\
        gen_pattern64_1em_rm_idx(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern64_1em_op_idx(0xF7, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } 

#define gen_func_body_arith_incdec(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx(0xFE, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx(0xFE, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx_word(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx_word(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register src) { \
        gencleanerdata\
        gen_pattern32_1em_rm_idx(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& src) { \
        gencleanerdata\
        gen_pattern32_1em_op_idx(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register src) {\
        gencleanerdata\
        gen_pattern64_1em_rm_idx(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& src) {  \
        gencleanerdata\
        gen_pattern64_1em_op_idx(0xFF, src, type)\
        gen_func_return(cap_id, cap_eflags)\
    }

#define gen_func_body_shift(name ,type, cap_id, cap_eflags) \
     fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_b)(fuku_register dst) {\
       gencleanerdata\
       gen_pattern32_1em_rm_idx(0xD2, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
     fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_b)(const fuku_operand& dst) {\
       gencleanerdata\
       gen_pattern32_1em_op_idx(0xD2, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b)(fuku_register dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD0); \
          emit_modrm(dst, type);\
       }else {\
          emit_b(0xC0); \
          emit_modrm(dst, type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_b)(const fuku_operand& dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD0); \
          emit_operand(dst, (fuku_register_index)type);\
       }else {\
          emit_b(0xC0); \
          emit_operand(dst, (fuku_register_index)type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
\
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_w)(fuku_register dst) {\
       gencleanerdata\
       gen_pattern32_1em_rm_idx_word(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
     fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_w)(const fuku_operand& dst) {\
       gencleanerdata\
       gen_pattern32_1em_op_idx_word(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w)(fuku_register dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_modrm(dst, type);\
       }else {\
          emit_b(0xC1); \
          emit_modrm(dst, type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w)(const fuku_operand& dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_operand(dst, (fuku_register_index)type);\
       }else {\
          emit_b(0xC1); \
          emit_operand(dst, (fuku_register_index)type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_dw)(fuku_register dst) {\
       gencleanerdata\
       gen_pattern32_1em_rm_idx(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
     fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_dw)(const fuku_operand& dst) {\
       gencleanerdata\
       gen_pattern32_1em_op_idx(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw)(fuku_register dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_modrm(dst, type);\
       }else {\
          emit_b(0xC1); \
          emit_modrm(dst, type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw)(const fuku_operand& dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_optional_rex_32(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_operand(dst, (fuku_register_index)type);\
       }else {\
          emit_b(0xC1); \
          emit_operand(dst, (fuku_register_index)type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_qw)(fuku_register dst) {\
       gencleanerdata\
       gen_pattern64_1em_rm_idx(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
     fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_cl_qw)(const fuku_operand& dst) {\
       gencleanerdata\
       gen_pattern64_1em_op_idx(0xD3, dst, type)\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw)(fuku_register dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_rex_64(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_modrm(dst, type);\
       }else {\
          emit_b(0xC1); \
          emit_modrm(dst, type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } \
      fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw)(const fuku_operand& dst, const fuku_immediate& src) {\
       gencleanerdata\
       emit_rex_64(dst);\
       if(is_used_short_imm() && src.get_immediate8() == 1) {\
          emit_b(0xD1); \
          emit_operand(dst, (fuku_register_index)type);\
       }else {\
          emit_b(0xC1); \
          emit_operand(dst, (fuku_register_index)type);\
          emit_immediate_b(src);\
       }\
       gen_func_return(cap_id, cap_eflags)\
     } 

#define gen_func_body_bit(name ,type, cap_id, cap_eflags) \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_optional_rex_32(dst, src);\
        emit_b(0x0F);\
        emit_b(0x83 + 8*type);\
        emit_modrm(dst, src);\
        gen_pattern32_2em_rm_r_word(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_optional_rex_32(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_modrm(dst, type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_2em_op_r_word(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_w) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_optional_rex_32(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_operand(dst, (fuku_register_index)type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_2em_rm_r(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_optional_rex_32(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_modrm(dst, type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern32_2em_op_r(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_dw) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_optional_rex_32(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_operand(dst, (fuku_register_index)type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern64_2em_rm_r(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (fuku_register dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_rex_64(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_modrm(dst, type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& dst, fuku_register src) { \
        gencleanerdata\
        gen_pattern64_2em_op_r(0x0F, 0x83 + 8*type, dst, src)\
        gen_func_return(cap_id, cap_eflags)\
    } \
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,_qw) (const fuku_operand& dst,const fuku_immediate& src) { \
        gencleanerdata\
        emit_rex_64(dst);\
        emit_b(0x0F);\
        emit_b(0xBA);\
        emit_operand(dst, (fuku_register_index)type);\
        emit_immediate_b(src);\
        gen_func_return(cap_id, cap_eflags)\
    } 


#define gen_func_body_string_inst(name ,type, cap_idMASK, cap_eflags)\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,b) () { \
        gencleanerdata\
        emit_b(type*2);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,B), cap_eflags)\
    }\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,w) () { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_b(type*2 + 1);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,W), cap_eflags)\
    }\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,d) () { \
        gencleanerdata\
        emit_b(type*2 + 1);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,D), cap_eflags)\
    }\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,q) () { \
        gencleanerdata\
        emit_rex_64();\
        emit_b(type*2 + 1);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,Q), cap_eflags)\
    }

#define gen_func_body_string_inst_withoutq(name ,type, cap_idMASK, cap_eflags)\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,b) () { \
        gencleanerdata\
        emit_b(type*2);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,B), cap_eflags)\
    }\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,w) () { \
        gencleanerdata\
        emit_b(FUKU_PREFIX_OVERRIDE_DATA);\
        emit_b(type*2 + 1);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,W), cap_eflags)\
    }\
    fuku_asm_ret_type fuku_assambler:: fuku_asm_gen_name(_,name,d) () { \
        gencleanerdata\
        emit_b(type*2 + 1);\
        gen_func_return(fuku_asm_gen_name(,cap_idMASK,D), cap_eflags)\
    }
    
